name: Website Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'website/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '13' ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup GIT
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "$GITHUB_ACTOR"
    - run: npm install
      working-directory: ./website
    - run: npm run deploy
      working-directory: ./website
      env:
       CI: true
